feat: feat 45 logging in action

diff --git a/.github/workflows/sync-release.yaml b/.github/workflows/sync-release.yaml
--- a/.github/workflows/sync-release.yaml
+++ b/.github/workflows/sync-release.yaml
@@ -42,8 +42,8 @@ jobs:
       
       - name: create pull request for major or minor release
         run: |
-          COMMIT_OVERRIDE1=$(git rev-list --reverse --pretty="%s" --cherry-pick --right-only ${PR_BRANCH}...origin/main | grep -v "commit" | grep -v "chore: sync #" || echo "")
-          COMMIT_OVERRIDE2=$(git rev-list --reverse --pretty="%s" --cherry-pick --right-only origin/main...${PR_BRANCH} | grep -v "commit" | grep -v "chore: release" || echo "")
+          COMMIT_OVERRIDE1=$(git rev-list --reverse --pretty="%s" --cherry-pick --right-only ${PR_BRANCH}...origin/main | grep -v "commit" | grep -v "chore: sync #" || echo "fail1")
+          COMMIT_OVERRIDE2=$(git rev-list --reverse --pretty="%s" --cherry-pick --right-only origin/main...${PR_BRANCH} | grep -v "commit" | grep -v "chore: release" || echo "fail2")
           
           echo "# Description" >> body
           echo "" >> body
@@ -64,26 +64,3 @@ jobs:
           --base main \
           --head $PR_BRANCH \
           --assignee '${{ github.event.pull_request.merged_by.login }}'
-      
-      # - name: create pull request for patch release
-      #   if: ${{ ! endsWith(env.RELEASE_TAG, '.0') }}
-      #   run: |
-      #     COMMIT_OVERRIDE1=$(git rev-list --reverse --pretty="%s" --cherry-pick --right-only origin/main...${PR_BRANCH} | grep -v "commit" | grep -v "chore: release" || echo "")
-      #     COMMIT_OVERRIDE2=$(git rev-list --reverse --pretty="%s" --cherry-pick --right-only origin/main...${PR_BRANCH} | grep -v "commit" | grep -v "chore: release" || echo "")
-
-      #     echo "# Description" >> body
-      #     echo "" >> body
-      #     echo "Syncing patch release ${RELEASE_TAG} to main branch" >> body
-      #     echo "" >> body
-      #     echo "**↓↓ Please review and edit commit overrides before merging ↓↓**" >> body
-      #     echo "" >> body
-      #     echo "BEGIN_COMMIT_OVERRIDE" >> body
-      #     echo "${COMMIT_OVERRIDE}" >> body
-      #     echo "END_COMMIT_OVERRIDE" >> body
-          
-      #     gh pr create \
-      #     --title "chore: sync release ${RELEASE_TAG} to main branch" \
-      #     --body "$(cat body)" \
-      #     --base main \
-      #     --head $PR_BRANCH \
-      #     --assignee '${{ github.event.pull_request.merged_by.login }}'
